CREATE TABLE IF NOT EXISTS "user"
(
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255),
    name VARCHAR(255),
    verified BOOLEAN DEFAULT FALSE,
    verification_code VARCHAR(6),
    picture VARCHAR(2000) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
